import "bootstrap-icons/font/bootstrap-icons.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "aos/dist/aos.css";
import type { Metadata } from "next";
import { EB_Garamond } from "next/font/google";
import Header from "@/components/Header";
import "./variables.css";
import "./globals.css";

// Inisialisasi font EB Garamond dengan subset Latin
const ebGaramond = EB_Garamond({ subsets: ["latin"] });

// Metadata untuk halaman
export const metadata: Metadata = {
  title: "KPU News App",
  description: "Generated by create next app",
};

// Komponen RootLayout
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ebGaramond.className}>
        {/* Komponen Header */}
        <Header />
        {/* Konten anak */}
        {children}
      </body>
    </html>
  );
}
